more explicit failures

diff --git a/src/test/eiffel/ci b/src/test/eiffel/ci
--- a/src/test/eiffel/ci
+++ b/src/test/eiffel/ci
@@ -21,19 +21,28 @@ echo $log
     echo "======================================================================"
     echo "test note heads"
     echo
-    ./test note $CI_CLEAN || failures=$((failures+1))
+    ./test note $CI_CLEAN || {
+        echo 'note FAILED!'
+        failures=$((failures+1))
+    }
 
     for i in 1 2 4 5 6 7; do # test 3 was removed
         echo "======================================================================"
         echo "test $i"
         echo
-        ./test $i $CI_CLEAN || failures=$((failures+1))
+        ./test $i $CI_CLEAN || {
+            echo $i' FAILED!'
+            failures=$((failures+1))
+        }
     done
 
     echo "======================================================================"
     echo "test lily"
     echo
-    ./test lily $CI_CLEAN || failures=$((failures+1))
+    ./test lily $CI_CLEAN || {
+        echo 'lily FAILED!'
+        failures=$((failures+1))
+    }
 
     echo "======================================================================"
     echo "build"
@@ -54,20 +63,21 @@ echo $log
                     if test -e $ly; then
                         if test -e $EXAMPLES_DIR/reference/$ly; then
                             diff -u $EXAMPLES_DIR/reference/$ly $ly || {
-                                echo "Different from reference!"
+                                echo "FAILED: different from reference!"
                                 failures=$((failures+1))
                             }
                         fi
                     else
-                        echo "Missing $ly! Failed execution?"
+                        echo "FAILED: Missing $ly!"
                         failures=$((failures+1))
                     fi
                 else
+                    echo "mixup $mix FAILED!"
                     failures=$((failures+1))
                 fi
             done
         else
-            echo "Missing build directory! Failed packaging?"
+            echo "FAILED: missing build directory!"
             failures=$((failures+1))
         fi
 
