Yell louder when a test fails.

diff --git a/src/test/eiffel/ci b/src/test/eiffel/ci
--- a/src/test/eiffel/ci
+++ b/src/test/eiffel/ci
@@ -33,3 +33,5 @@ echo $log
         echo "Failures: $failures"
     fi
 } >$log 2>&1
+
+tail -n 1 $log | grep SUCCESS || echo 'FAILED!'
